kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: example
  namespace: nvidia
spec:
  nodeSelector: null
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: HTTP_PROXY
          value: 'http://myproxy.net:5187/'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/spankes/nvd-driver.git'
      ref: master
  triggers:
    - type: ConfigChange
  runPolicy: Serial
