kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nvd-driver-custom-bc 
  namespace: gpu-operator-resources
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: >-
        image-registry.openshift-image-registry.svc:5000/gpu-operator-resources/nvd-driver-custom:440.64.00-rhcos4.4
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: TEST
          value: test
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/spankes/nvd-driver.git'
      ref: master
  triggers: []
  runPolicy: Serial
